site_name: GraphShield | Docs
site_url: https://docs.graphshield.io
repo_url: https://github.com/guillaumemeyer/docs/
# repo_name: GitHub
docs_dir: public
site_dir: docs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
  plugins:
    - search:
        lang: en
  scheme: default # Slate === dark
  palette:
    primary: black # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
    accent: red